require: rubocop-rails
AllCops:
  TargetRubyVersion: 2.5
  Exclude: ['vendor/**/*']
Documentation:
  Enabled: false
Metrics/LineLength:
  IgnoredPatterns:
    - '\A\s*#'
    - '\A\s*puts'
Rails/Output:
  Enabled: false
